DEVENGAGE-765 Partial transcription blogpost
MyPureCloud/developer-center-blog pull request #102
Opened 2022-02-16 18:17 UTC by diemenschmaschine92

Blogpost for partial transcription blueprint

2022-02-16 20:28 UTC, timsmithgenesys requested changes

2022-02-16 20:28 UTC, timsmithgenesys commented on source/2022-02-16-partial-transcription-notifications-in-client-app-integration/index.md
> +"](https://help.mypurecloud.com/articles/set-custom-client-application-integration/).
there can't be a line break inside the link

2022-02-16 20:28 UTC, timsmithgenesys commented on source/2022-02-16-partial-transcription-notifications-in-client-app-integration/index.md
> +The next step will depend on the client-side language you choose.  The upcoming blueprint on the subject uses a React+TypeScript base, so it requires the [Platform API Javascript Client](https://gith
Just link to the npm package. That page links back to the github project if people want to look into it.

2022-02-22 16:28 UTC, carnellj approved these changes

2022-02-22 16:28 UTC, carnellj commented on source/2022-02-16-partial-transcription-notifications-in-client-app-integration/index.md
> +- A dashboard that gathers metrics based on call transcripts.  E.g. - If you want agents to greet all customers with a particular greeting, what is the percentage of calls where said greeting is made
We should add an additional resources section:

1.  The DevDrop introducing the Partial Transcript.
2. The help center document on partial transcript.
3. Link to the github repo (Just put Draft in this title)

2022-02-22 19:44 UTC, timsmithgenesys approved these changes

2022-02-22 20:21 UTC, merged