Devengage 1163 dev ops antipatterns
MyPureCloud/developer-center-blog pull request #110
Opened 2022-05-16 14:53 UTC by carnellj

2022-05-17 17:40 UTC, timsmithgenesys commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +Greetings everyone! 2022 is flying by. The year is almost half-gone. Today, I want to spend sometime talking about DevOps best practices and how they can be applied to your **CX as Code** implementat
sometime -> some time

2022-05-17 17:42 UTC, timsmithgenesys commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +One of the more common mistakes I see new DevOps practitioners make is that put all of their infrastructure declarations for **CX as Code** as one or two big Terraform project all managed from a sing
two bit Terraform project -> two bit Terraform project**s** (s++)

2022-05-17 18:07 UTC, timsmithgenesys requested changes
You asked for nitpicks, you got em. :)

2022-05-17 18:07 UTC, timsmithgenesys commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. [Install CX as Code](https://developer.genesys.cloud/api/rest/CX-as-Code/). General Instructions for installing Terraform.
1. Don't include the dev center host in links (i.e. `https://developer.genesys.cloud`)
2. That path is outdated. The correct location for that page is now `/devapps/cx-as-code/`

2022-05-17 18:07 UTC, timsmithgenesys commented on source/2022-05-12-devops-antipatterns/index.md
> +title: CX as Code and DevOps Best Practices
Is this supposed to be checked in? It looks like an earlier draft of the other blog post in this PR.

2022-05-18 15:24 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +
Done.  Cool about the line items.  I was relying on a VSCode extension that rendered the markdown and it wasn't exhibiting that behavior so that was a good catch

2022-05-18 19:51 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +Decompose your CX infrastructure down into small deployable units of work that mirror the natural communication structure of your organization. This is often referred to an [Conway's law](https://en.
Done.  I seem to randomly drop's and don't realize it.

2022-05-18 19:51 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +![alt text](decomposed-repositories.png "Decomposed repositories")
Done

2022-05-18 19:51 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +This is one of the hardest changes for many organizations to make. If you are going to use **CX as Code** to manage a piece of your Genesys Cloud infrastructure, you need to ensure that all changes t
Done.

2022-05-18 20:08 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +By giving into this temptation, you are introducing configuration drift and you begin an endless cycle of trying to keep your environments in sync. At first this might not seem like a big deal. After
Done.

2022-05-18 20:21 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. **Your development Genesys Cloud environment should be a sandbox to try things out. Once your developers have manually experimented with something, they should put their Architect flows and CX as
Done

2022-05-18 20:28 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. [Install CX as Code](https://developer.genesys.cloud/api/rest/CX-as-Code/). General Instructions for installing Terraform.
Done

2022-05-18 20:28 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +3. [Introducing CX as Code](https://developer.genesys.cloud/blog/2021-04-16-cx-as-code/) Blog Post.
Done

2022-05-18 20:28 UTC, carnellj commented on source/2022-05-12-devops-antipatterns/index.md
> +title: CX as Code and DevOps Best Practices
Oops.  Good catch.  That should have been deleted.

2022-05-18 21:24 UTC, timsmithgenesys commented on source/2022-05-12-devops-antipatterns/index.md
> +title: CX as Code and DevOps Best Practices
friendly reminder to delete this folder

2022-05-19 13:35 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +One of the more common mistakes I see new DevOps practitioners make is that put all of their infrastructure declarations for **CX as Code** as one or two big Terraform project all managed from a sing
Fixed

2022-05-19 13:45 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +Greetings everyone! 2022 is flying by. The year is almost half-gone. Today, I want to spend some time talking about DevOps best practices and how they can be applied to your **CX as Code** implementa
half gone (no hyphen)

2022-05-19 13:46 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +One of the more common mistakes I see new DevOps practitioners make is that put all of their infrastructure declarations for **CX as Code** as one or two big Terraform projects, all managed from a si
is that they put (add pronoun)

2022-05-19 13:49 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. **You have created a single monolith infrastructure where changes to one part of your CX infrastructure require the entire CX infrastructure to be deployed at the same time**. This means that if y
You have created a single monolithic (adj. form)
This means that if you have multiple  (missing verb)
because if you try to roll back a change, you roll back (roll back is 2 words when used as a verb)
velocities, and tying all of (add comma between two complementary clauses)

2022-05-19 13:50 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +2. **It is easy to create implicit cross-component dependencies because your entire CX infrastructure is defined in a single project and as a result developers can easily reference another component
ingle project, and as a result developers (need a comma)
(for example, a queue, skill, language, and so on) (replace Latin phrases with English)

2022-05-19 13:51 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +
Use bullets for this list. It gets confusing later when you use numbers again.

2022-05-19 14:20 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +This way different pieces of code (e.g. your flows) can be deployed independently of one another.
Remove this sentence.

2022-05-19 14:24 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +This is one of the hardest changes for many organizations to make. If you are going to use **CX as Code** to manage a piece of your Genesys Cloud infrastructure, you need to ensure that all changes t
Do you need the second half of this sentence after the **and**: 
you need to ensure that all changes to that infrastructure are managed through the source control system **and** all changes are deployed from the source control system.

2022-05-19 14:26 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +By giving in to this temptation, you are introducing configuration drift and you begin an endless cycle of trying to keep your environments in sync. At first this might not seem like a big deal. Afte
"Hey,...
However, people get busy, they are not infallible, and changes do not get...
...begin losing confidence in the overall integrity of your system (instead of different environments)

2022-05-19 14:30 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +Terraform, the technology **CX as Code** is built on, expects to be the sole maintainer of the state of objects that it owns. If you manually modify an object that Terraform/**CX as Code** maintains
Terraform, the technology upon which **CX as Code** is built, expects to be the sole maintainer of the state of the objects that it owns. If you manually modify a maintained object, then the next time you run your Terraform script, Terraform will revert the object back its prior state. For example, let's say you create and manage a queue through Terraform. If you go into the console and add additional routing rules to the queue. If you do not add those configuration changes in your **CX as Code** definitions, the next time you do a deploy via your CI/CD pipeline, those manually-added definitions will be lost. Long story short, manually modifying a Terraform managed object is a bad idea and can cause an outage: **don't do it.**

2022-05-19 14:40 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +If you are constantly have to "snapshot" your production environment and sync it back your development and test Genesys Cloud accounts you are not using your source control system to drive changes. A
Continuing...
A healthy DevOps practitioner uses source control to drive changes instead. This ensures that development, test, and production environments retain their integrity.

2022-05-19 15:39 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +Greetings everyone! 2022 is flying by. The year is almost half-gone. Today, I want to spend some time talking about DevOps best practices and how they can be applied to your **CX as Code** implementa
Done

2022-05-19 15:40 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +One of the more common mistakes I see new DevOps practitioners make is that put all of their infrastructure declarations for **CX as Code** as one or two big Terraform projects, all managed from a si
Done

2022-05-19 15:42 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. **You have created a single monolith infrastructure where changes to one part of your CX infrastructure require the entire CX infrastructure to be deployed at the same time**. This means that if y
Done.  Please double check and if code mark as resolved

2022-05-19 15:44 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +
Done

2022-05-19 15:46 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +To apply Conway's law and look at how you contact centers code maps to a functional area, I recommend you start with your Architect flows. Your Architect flows represent a natural division of respons
Perfect

2022-05-19 15:47 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +This is one of the hardest changes for many organizations to make. If you are going to use **CX as Code** to manage a piece of your Genesys Cloud infrastructure, you need to ensure that all changes t
Fixed

2022-05-19 15:53 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +2. **Lockdown your test and production environments so that only a very, very small number of people can make changes. Too often organizations do not take time to properly build out their Access Cont
Lock down (2 words)
access control (lowercase)
...it can ruin your confidence in the consistency of your environments.

2022-05-19 15:53 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +2. **Lockdown your test and production environments so that only a very, very small number of people can make changes. Too often organizations do not take time to properly build out their Access Cont
Done!

2022-05-19 15:54 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +4. **Not everything in your Genesys Cloud environment should be managed with CX as Code**. Things that change multiple times a day should not be put under **CX as Code** management because those chan
..multiple times a day, you probably... (add comma)

2022-05-19 15:54 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +The diagram below illustrates this decomposition is action:
Done

2022-05-19 15:55 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +If you are constantly have to "snapshot" your production environment and sync it back your development and test Genesys Cloud accounts you are not using your source control system to drive changes. A
Done

2022-05-19 16:08 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +5. **Automate, automate, automate. There should be no manual parts to your CI/CD pipeline.** Once code is committed to your source control repository, the robots (aka your deployment scripts). There
Done

2022-05-19 16:09 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. **Group shared dependencies with high cohesion into the same repository**. For example, if you have skills that are used across multiple flows create a skills repository with all of your skills de
For example, if you have skills that are used across multiple flows create a single skills repository to maintain them centrally.

These sentences confused me--can you wordsmith?
Don't intermix different shared CX as Code resources together in the same repositories. This creates artificial deployment dependencies.

2022-05-19 16:11 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +As you tease apart configurations minimize the amount of shared components between your Architect flows. Minimizing these shared dependencies avoids deployment dependencies. Also, don't be afraid to
Done

2022-05-19 16:14 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +2. **Remember many shared dependencies can be deploy independently of the things consuming them and get often be deployed ahead of time with minimal risk**. So for instance, if you have a shared defi
**Remember: You manage shared dependences separately from the objects that consume then. This means that you can deploy shared dependencies separately, often ahead of time, with minimal risk**. For example, if you have a shared definition of languages, you can deploy the language changes independently from the flows and scripts that consume them. Deploy these changes frequently and get those changes out there.

2022-05-19 16:18 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +3. **Use a pull request model for changes to shared resources**. Often times organizations will centralize control of shared resources and only allow those resources to be directly changed by that gr
**Use a pull request model for changes to shared resources**. Organizations often centralize control of shared resources and allow only the members of the designated team to update them. Unless the shared resources are extremely sensitive (for example, credentials management), leverage your source control system's pull request mechanism instead to enable anyone to branch the code, make changes, and submit a pull request. The designated team should be responsible for reviewing the changes and merging them into the master branch. However, the actual work of updating the resources should go to the team who needs the updates.

2022-05-19 16:20 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +**CX as Code** (and the Terraform project it is built on) does not have the concept of environmental snapshots and the ability to rollback code to a specific version. If you discover a problem in you
**CX as Code** support the ability to roll back an environment to a specific snapshotted version. If you discover a problem in your deployments, I highly recommend a "move forward" model where you make the fix in your lower environments and then promote and deploy the fix to the production environments. If you do need to rollback to a previous version keep the following in mind:

2022-05-19 16:21 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +2. **If you are not deploying back to the previous version of your configuration, make sure you understand what has changed between between the production releases**. Run a `terraform plan` before do
2. **If you are not deploying back to the previous version of your configuration, make sure you understand what has changed between between the production releases**. Run a `terraform plan` command before doing the rollback, and make sure you don't inadvertently drop a resource that was created between releases.

2022-05-19 16:23 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +3. **Leverage automated testing as part of your deployment pipeline.** Whenever possible kickoff automated tests to check your code and infrastructure after it has been deployed. This includes in pro
3. **Leverage automated testing as part of your deployment pipeline.** Whenever possible kick off automated tests to check your code and infrastructure after it has been deployed. perform these automated tests in your production environment. These automated tests provide a quick feedback loop that confirms that your deployment worked. Simple, automated tests also reduce the risk of making hasty decisions (such as using the console to make changes) because you are under pressure to fix an issue during critical business hours.

Do the automated tests reduce the risk of using the console, or do they reduce the risk of errors that are introduced when the dev makes the hasty decision?

2022-05-19 16:25 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +**CX as Code** is a set of low-level primitives for building CI/CD deployment solutions with Genesys Cloud. It is not a shrink-wrapped Disaster Recovery (DR), backup, or migration tool. It can be use
**CX as Code** is a set of low-level primitives for building CI/CD deployment solutions with Genesys Cloud. These set of primitives does not comprise a shrink-wrapped Disaster Recovery (DR), backup, or migration tool. It can be used to help build these type of solutions, but this type of tooling is specific to your organization, takes time to be developed, and must be tested on a regular basis. Do not make assumptions about how **CX as Code** (or any CI/CD tool) works. While DevOps and CI/CD practices can provide a high-level of stability and confidence in your environment, they do not eliminate or minimize the need for IT folks. DevOps is a practice within IT, not a replacement for it.

2022-05-19 16:26 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +journey iterate and learn. Mistakes will be made, but it is better to make small mistakes along the way then try to "go big" and then find out you have created a monolith that does not add value, but
remove extra line between 79-80

2022-05-19 16:26 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +
Where's that Linter? We need accessibility text for all these links. On it...

2022-05-19 17:02 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +3. [Introducing CX as Code](/blog/2021-04-16-cx-as-code/) Blog Post.
[Introducing CX as Code blog post](/blog/2021-04-16-cx-as-code/ "Goes to the Introducing CX as Code blog post)

2022-05-19 17:04 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +4. [Managing your customer experience as code](https://www.youtube.com/watch?v=21p6hDFipKY&t=1470s)
[DevCast Tutorial 19: Managing your Customer Experience as Code: Introducing CX as Code](https://www.youtube.com/watch?v=21p6hDFipKY&t=1470s "Goes to the Introducing CX as Code YouTube video")

2022-05-19 17:06 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +5. [HelloWorld CX as Code Blueprint](https://github.com/GenesysCloudBlueprints/simple-ivr-deploy-with-cx-as-code-blueprint). A blueprint that demonstrates how to set up a very Simple IVR with CX as C
5. [Deploy a simple IVR using Terraform, CX as Code, and Archy Blueprint](https://github.com/GenesysCloudBlueprints/simple-ivr-deploy-with-cx-as-code-blueprint "Goes to the Deploy a simple IVR using Terraform, CX as Code, and Archy blueprint"). A blueprint that demonstrates how to set up a very Simple IVR with CX as Code. It is meant to be a "Hello World"-style application.

2022-05-19 17:11 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. **Group shared dependencies with high cohesion into the same repository**. For example, if you have skills that are used across multiple flows create a skills repository with all of your skills de
Done

2022-05-19 17:12 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +2. **Remember many shared dependencies can be deploy independently of the things consuming them and get often be deployed ahead of time with minimal risk**. So for instance, if you have a shared defi
Done

2022-05-19 17:13 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +**CX as Code** (and the Terraform project it is built on) does not have the concept of environmental snapshots and the ability to rollback code to a specific version. If you discover a problem in you
Done

2022-05-19 17:16 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +3. **Leverage automated testing as part of your deployment pipeline.** Whenever possible kickoff automated tests to check your code and infrastructure after it has been deployed. This includes in pro
Done.  Supposed to detect deployment issues.  The point here is that if you deploy during the evening and then do not find the issue until the mid-day you are going to be tempted to do the wrong thing and go into the console

2022-05-19 17:17 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +journey iterate and learn. Mistakes will be made, but it is better to make small mistakes along the way then try to "go big" and then find out you have created a monolith that does not add value, but
fixed

2022-05-19 17:17 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +6. [Standalone CX as Code Blueprint](/blueprints/email-aws-comprehend-blueprint/). A more advanced blueprint that shows deploying a flow and its dependent objects, including queues and data actions.
6. [Classify and route emails with Amazon Comprehend Blueprint](/blueprints/email-aws-comprehend-blueprint/ "Goes to the Classify and route emails with Amazon Comprehend Blueprint"). A more advanced blueprint that shows a standalone CX as Code implementation in which you deploy a flow and its dependent objects, including queues and data actions.

2022-05-19 17:19 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +7. [CI/CD Example with CX as Code Blueprint](/blueprints/cx-as-code-cicd-gitactions-blueprint/). This blueprint demonstrates how to build a CI/CD pipeline using Github Actions, Terraform Cloud, and C
[Build a CI/CD pipeline using GitHub Actions, Terraform Cloud, CX as Code, and Archy Blueprint](/blueprints/cx-as-code-cicd-gitactions-blueprint/ "Goes to the Build a CI/CD pipeline using GitHub Actions, Terraform Cloud, CX as Code, and Archy Blueprint). This blueprint demonstrates how to build a CI/CD pipeline that deploys Genesys Cloud objects across multiple Genesys Cloud organizations.

2022-05-19 17:19 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +8. [Conway's Law](https://en.wikipedia.org/wiki/Conway%27s_law "Conway's Law")
8. [Conway's Law](https://en.wikipedia.org/wiki/Conway%27s_law "Conway's Law" "Goes to the Conway's law article in Wikipedia)

2022-05-19 17:20 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +3. [Introducing CX as Code](/blog/2021-04-16-cx-as-code/) Blog Post.
Fixed all missing Accessibility text

2022-05-19 17:20 UTC, DannaShirley commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +9. [How to begin your CX as Code Journey](/blog/2021-10-10-treating-contact-center-infrastructure-as-code/ "How to begin your CX as Code Journey"). A blog post that helps provide guidance to the read
9. [How to begin your CX as Code Journey](/blog/2021-10-10-treating-contact-center-infrastructure-as-code/ "Goes to the How to begin your CX as Code Journey blog post")

2022-05-19 17:21 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +5. [HelloWorld CX as Code Blueprint](https://github.com/GenesysCloudBlueprints/simple-ivr-deploy-with-cx-as-code-blueprint). A blueprint that demonstrates how to set up a very Simple IVR with CX as C
Done

2022-05-19 17:22 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +6. [Standalone CX as Code Blueprint](/blueprints/email-aws-comprehend-blueprint/). A more advanced blueprint that shows deploying a flow and its dependent objects, including queues and data actions.
Done

2022-05-19 17:23 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +8. [Conway's Law](https://en.wikipedia.org/wiki/Conway%27s_law "Conway's Law")
Done

2022-05-19 17:24 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +9. [How to begin your CX as Code Journey](/blog/2021-10-10-treating-contact-center-infrastructure-as-code/ "How to begin your CX as Code Journey"). A blog post that helps provide guidance to the read
Done

2022-05-19 17:24 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. [Install CX as Code](/devapps/CX-as-Code/). General Instructions for installing Terraform.
Done

2022-05-19 17:26 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +
The linter is for the blueprints.  I don't have a ruleset defined for blog posts :).  Sorry but your efforts are appreciated.

2022-05-19 17:27 UTC, carnellj commented on source/2022-05-12-cx-as-code-devops-best-practices/index.md
> +1. **Leverage your source control system.** Each time you deploy to production tag your build. If you need to rollback, redeploy that version of the source control repository.
Done

2022-05-19 18:11 UTC, merged