RELATE-6278: Adding blog post for single customer view
MyPureCloud/developer-center-blog pull request #113
Opened 2022-07-15 19:29 UTC by monitorjbl

2022-07-15 19:37 UTC, timsmithgenesys requested changes

2022-07-15 19:37 UTC, timsmithgenesys commented on source/2022-07-15-single-customer-view/index.md
> +author: andrew.johnson
@monitorjbl are you submitting this on Andrew's behalf?

2022-07-15 20:32 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +author: andrew.johnson
Yeah, I am. Andy wrote the bulk of this, but didn't have time to blogify it so I'm doing that part for him.

2022-07-15 20:32 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +image: genesys.png
There is a PR up to add it in Bitbucket.

2022-07-15 20:34 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +**Curated** contacts are the contacts you already know (and hopefully love). These are created via the API, the web application/desktop app, or via CSV/Salesforce imports. They never age out; you are
Good suggestion, will do.

2022-07-18 17:22 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +Identity resolution can never be foolproof. A customer may have multiple devices that they use to contact your organization. Until they have been assigned to the contact that represents them, or if t
> ... or if the interaction contains extra information that can be used to associate it to a known contact, the platform will assume that the new device is a new person.

This seems incorrect.  If the interaction contains extra information that can be used to associate it to a known person, it *will not* create a new contact.  Guessing this is some sort of typo.

2022-07-18 17:23 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +To do this, you can merge two contacts that represent the same individual using the [`POST /api/v2/externalcontacts/merge/contacts`](/platform/preview-apis#post-api-v2-externalcontacts-merge-contacts
To do "this" -- what does "this" refer to?  "some manual intervention" from the previous sentence?

2022-07-18 17:28 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +Merging is gated behind a separate permission and endpoint, so it's not something that will happen unless your organization explicitly chooses to grant users permission to do it. Autogenerated contac
Change "grant users" to "grant agents"

2022-07-18 17:31 UTC, andrewtjohnson requested changes
Requested feedback in individual comments.

2022-07-18 17:43 UTC, andrewtjohnson requested changes
Left requested changes in comments.

2022-07-19 13:14 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +Merging is gated behind a separate permission and endpoint, so it's not something that will happen unless your organization explicitly chooses to grant users permission to do it. Autogenerated contac
Is that preferable? Not all users are agents.

2022-07-19 14:04 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +tags: Genesys Cloud, Developer Engagement, Usage API
It was in the template, I think. Will remove it

2022-07-19 14:06 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +To do this, you can merge two contacts that represent the same individual using the [`POST /api/v2/externalcontacts/merge/contacts`](/platform/preview-apis#post-api-v2-externalcontacts-merge-contacts
Fixed

2022-07-19 14:32 UTC, timsmithgenesys commented on source/2022-07-15-single-customer-view/index.md
> +author: andrew.johnson
@andrewtjohnson no, posts can only have a single author.

2022-07-19 15:00 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +* [`GET /api/v2/externalcontacts/contacts/{contactId}`](https://developer.genesys.cloud/commdigital/externalcontacts/externalcontacts-apis#get-api-v2-externalcontacts-contacts--contactId-)
Is there a way to build this site locally so I can see what it looks like in my document?

2022-07-19 15:55 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +* [`GET /api/v2/externalcontacts/contacts/{contactId}`](https://developer.genesys.cloud/commdigital/externalcontacts/externalcontacts-apis#get-api-v2-externalcontacts-contacts--contactId-)
Tim showed me a way to preview this. It looks like the choice is between this:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1149136/179794810-3a62999c-ba44-4bf0-96e0-56b92caacad0.png">

and this:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1149136/179794909-74be0a0f-a61f-4515-8c6a-7f14c01d56c4.png">

I prefer the latter, the former takes up a lot of space without much purpose. It's unlikely anyone reading this post will actually try to execute these endpoints directly from the page.

2022-07-20 15:42 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +Until now, the way to look up contacts by identifiers like phone number, email address, etc. has been to use the [`GET /api/v2/externalcontacts/reversewhitepageslookup`](/commdigital/externalcontacts
Do we need the backticks in the markdown links here?  Will that affect the rendering of links?

2022-07-20 15:44 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +Identity resolution can never be foolproof. A customer may have multiple devices that they use to contact your organization. Until they have been assigned to the contact that represents them, or if t
Let's talk through this on a call.  The revised version does not quite make sense to me, either.

2022-07-20 15:48 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +Identity resolution can never be foolproof. A customer may have multiple devices that they use to contact your organization. Until they have been assigned to the contact that represents them, or if t
Oh, I think it's the command.  The middle statement in the original binds left, not right.  I think the comma in ", or if the interaction contains extra information" needs to be removed.  Ed can advise here.  I thought that clause went with the following statement, which would make it incorrect.

Maybe there's a way to reword the whole thing to make it clearer and put all the exception stuff last after an "unless".

<normal thing that happens> unless <exception case 1> <exception case 2>.

2022-07-20 15:51 UTC, timsmithgenesys commented on source/2022-07-15-single-customer-view/index.md
> +Until now, the way to look up contacts by identifiers like phone number, email address, etc. has been to use the [`GET /api/v2/externalcontacts/reversewhitepageslookup`](/commdigital/externalcontacts
Need? No. You're making a style choice here. Links and inline code are rendered the same in github vs dev center. Examples:

With backticks: [`GET /api/v2/externalcontacts/reversewhitepageslookup`](/commdigital/externalcontacts/externalcontacts-apis#get-api-v2-externalcontacts-reversewhitepageslookup)

Without: [GET /api/v2/externalcontacts/reversewhitepageslookup](/commdigital/externalcontacts/externalcontacts-apis#get-api-v2-externalcontacts-reversewhitepageslookup)

2022-07-20 16:14 UTC, andrewtjohnson requested changes
here is my overall review comment

2022-07-20 16:14 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +You can read more about identifiers and their associated operations in our [developer documentation](/commdigital/externalcontacts/contact-merges#identifiers).
testing what "Start a review" means

2022-07-20 16:14 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +When the platform receives a new interaction on a supported channel, it resolves the identifiers for that interaction (for example: phone number, email address, social media identifier, etc.) to a co
here is a review comment

2022-07-20 16:16 UTC, andrewtjohnson approved these changes

2022-07-20 16:22 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +Identity resolution can never be foolproof. A customer may have multiple devices that they use to contact your organization. Unless those devices have been assigned to the contact that represents the
unless (A or B)
vs
(unless A) or B

2022-07-20 16:25 UTC, andrewtjohnson commented on source/2022-07-15-single-customer-view/index.md
> +Identity resolution can never be foolproof. A customer may have multiple devices that they use to contact your organization. Unless those devices have been assigned to the contact that represents the
unless either (A or B), then

2022-07-20 18:13 UTC, monitorjbl commented on source/2022-07-15-single-customer-view/index.md
> +Until now, the way to look up contacts by identifiers like phone number, email address, etc. has been to use the [`GET /api/v2/externalcontacts/reversewhitepageslookup`](/commdigital/externalcontacts
Yeah, I personally like the inline code style for this so I went with it for all the endpoint links. It makes it more obvious that the entire phrase is together when linebreaks split it up. Plus, a monospaced font screams "this is for developers," so the eyes of more technically-minded folk will be drawn to these bits of of the document.

2022-07-22 14:05 UTC, carnellj-genesys approved these changes

2022-07-22 14:05 UTC, merged