Making of Synoptia -- NEW blog by Ram Sundaram
MyPureCloud/developer-center-blog pull request #127
Opened 2023-05-08 18:01 UTC by JaneHendricks

Please post to developer center

2023-05-08 19:18 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +# Making of Synoptia: New Genesys Cloud Service for Generative AI
don't duplicate the title in the body

2023-05-08 19:18 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +As we all know, since 2019, Transformers based approaches (such as OpenAI’s GPT, GPT-3 and now GPT-4) have taken the NLP world by storm. GPT-3 was built to handle back and forth conversations and cov
extra period at the end

2023-05-08 19:20 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +At a high level, Transformer architecture typically consists of an encoder and decoder. Encoder encodes the input text to a vector representation and can be thought of as an array of floating-point n
Not sure if this formatting is an error or intentional, but separate paragraphs must have a blank line in between them. This will be concatenated with the previous paragraph. There's another instance of this below also

2023-05-08 19:20 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +- Removing emojis from the text.
Remove periods from list items; these aren't sentences.

2023-05-08 19:29 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +title: Making of Synoptia - New Genesys Cloud Service for Generative AI
Is "Synoptia" the customer-facing name of a Genesys Cloud product approved by marketing? I've never heard of it and it's not returning any results in the Genesys Cloud product docs or on the corporate site. Assuming this is just the name of a backend service, the name must be scrubbed from this post and replace with the official name of the Genesys Cloud product or a generic reference to "Genesys Cloud backend services". This content is public-facing and must not contain any internal-only references or materials.

Additionally, the context of this post should discuss everything in terms of the public-facing Genesys Cloud feature and not in terms of a backend service. There should be little reason to reference any backend services at all because customers only interact with the Genesys Cloud Platform; the existence of individual microservices is intentionally opaque.

2023-05-08 19:33 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +title: Making of Synoptia - New Genesys Cloud Service for Generative AI
Developer blog posts are expected to include some technical information. Some sections should be added to discuss/demonstrate the Platform API resources for this feature and add links to them. Links to the Resource Center should also be included so readers can find additional information in the product documentation.

2023-05-08 19:34 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +7. The summary is presented to the agent through their desktop
Include links to this agent functionality

2023-05-08 19:35 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +6. After all processes are complete, we let the consuming services know that the summary is available
include links to the specific topic in the available topics docs on the dev center

2023-05-08 19:35 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +If you want to try Agent Assist’s auto-summary feature, you can do so through AppFoundry.
add a link to it

2023-05-08 19:36 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +Preprocessing and post processing are very important to ensure we extract maximum accuracy from the model. Some of what agents and customers type during a conversation would confuse the model. Some w
add colon at the end

2023-05-08 20:11 UTC, JaneHendricks commented on 2023-05-08RamSBlog/index.md
> +# Making of Synoptia: New Genesys Cloud Service for Generative AI
Resolved. Sorry!

2023-05-08 20:13 UTC, JaneHendricks commented on 2023-05-08RamSBlog/index.md
> +title: Making of Synoptia - New Genesys Cloud Service for Generative AI
Synoptia is an internal name for a service used in Genesys Agent Assist. It's fine for use in this developer blog. The purpose of this blog is to describe how we are using Generative AI and we are using it by creating our own service. This was done with Product Marketing support and is fine for this audience.

2023-05-08 20:50 UTC, JaneHendricks commented on 2023-05-08RamSBlog/index.md
> +title: Making of Synoptia - New Genesys Cloud Service for Generative AI
You're right that the name isn't relevant it's how it's built and the fact that it is used in Agent Assist and that it's our Generative AI service that we wrote (vs took from someone else). We can rewrite it to take the name out but it will be a lot less effective as a communication piece and it is not uncommon for vendors to talk about services that are used in their products that aren't exposed beyond the developer community. I can also see if we can add this to our documentation -- so that there is a mention of this name. The name itself is irrelevant as you say -- the explanation is what's important.

2023-05-08 21:18 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +title: Making of Synoptia - New Genesys Cloud Service for Generative AI
There are specific reasons we don't allow any internal services to be called out on the Developer Center:

* It causes confusion. When our documentation says Synoptia does this and Synoptia does that, it increases the support burden by needing to redirect all of those customers to the feature name they can find, which is Genesys Agent Assist. 
* Discussing internal architecture and specific details of non-public implementations is inappropriate for public-facing documentation. If a customer can't use it directly, we don't talk about it. Discussion of concepts implemented/executed by backend services for which the end result is observable is fine, but technical details that aren't exposed in our public-facing interfaces should be left out.
* It makes it look like vaporware and marketing fluff. When we talk about things that customers can't see and can't tell they're using, it gives the appearance that we just made it up. Specific to this situation, "AI" already has a big credibility problem since the term is thrown around carelessly in marketing materials throughout the tech industry. If a customer reads this post and doesn't understand microservice architectures and how we name backend services, they may think that Synoptia is just more AI vaporware since it doesn't actually exist as far as they can tell. Including links to the API endpoints to configure, train, and use this feature will directly demonstrate that this is a fully implemented AI feature.

2023-05-08 21:22 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +title: Making of Synoptia - New Genesys Cloud Service for Generative AI
> We can rewrite it to take the name out but it will be a lot less effective as a communication piece

To address this point specifically, I disagree that it will be less effective. You needn't be ambiguous; simply use the public-facing name and it will be more effective since it's more clear. It's acceptable to say "the agent assist service" and use it interchangeably with "the agent assist feature". An external audience is unable to observe that distinction.

2023-05-08 22:49 UTC, JaneHendricks commented on 2023-05-08RamSBlog/index.md
> +title: Making of Synoptia - New Genesys Cloud Service for Generative AI
okay. I'll rewrite it to say "Agent Assist Generative AI service" -- will that work?

2023-05-09 14:22 UTC, JaneHendricks reviewed
I've gone through and adjusted per feedback, added links to documentation and removed the service name. Please approve for posting.

2023-05-09 14:29 UTC, timsmithgenesys requested changes

2023-05-09 14:29 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +Preprocessing and post processing are very important to ensure we extract maximum accuracy from the model. Some of what agents and customers type during a conversation would confuse the model. Some w
Please address ☝️

2023-05-09 14:29 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +6. After all processes are complete, we let the consuming services know that the summary is available
Please address ☝️

2023-05-09 14:29 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +7. The summary is presented to the agent through their desktop
Please address ☝️

2023-05-09 14:37 UTC, timsmithgenesys commented on 2023-05-08RamSBlog/index.md
> +1. Once the agent ends the conversation in the UI, Synoptia receives the conversation details
remove Synoptia name. I missed a few because it's misspelled in some cases. Not sure if `syntopia` or `synoptia` is correct, but both occur in this document.

2023-05-09 15:48 UTC, timsmithgenesys commented
@JaneHendricks `2023-05-08-Generative AI in Agent Assist` isn't an appropriate folder name. Git accepts it, but using spaces makes for messy URI-encoded URLs and error-prone links. The words are fine, but it must not contain any spaces, and the typical format is lowercase letters and numbers using dashes between words. The note about folder naming in the readme uses the suggested format, but isn't doesn't state what the requirements actually are. I'll update that for clarity for future readers.

2023-05-09 15:59 UTC, timsmithgenesys commented
Please add links to the API resources and product docs. The developer blog targets a technical audience and needs to include the technical information about how customers can start using this feature and its API resources in their own applications.

2023-05-09 16:00 UTC, timsmithgenesys commented on 2023-05-08-Generative AI in Agent Assist/index.md
> +Preprocessing and post processing are very important to ensure we extract maximum accuracy from the model. Some of what agents and customers type during a conversation would confuse the model. Some w
missing colon

2023-05-09 16:08 UTC, JaneHendricks commented
There isn’t an api for agent assist – this is an explanation of how we are implementing Generative AI since we’ve had a lot of questions from the developer/technical community on how we are using Generative AI (which is new to us) – specifically whether this is the same as what OpenAI is doing, Google etc

We have links to the reference center for usage and customers would use this feature through Agent Assist
For the technical folks, the information on model type, where we sourced our data is critical – and is the kind of information only they would appreciate
I understand it’s a bit unusual but this is a necessary topic so hoping we can push this forward


Thanks

From: Tim Smith ***@***.***>
Sent: Tuesday, May 9, 2023 11:00 AM
To: MyPureCloud/developer-center-blog ***@***.***>
Cc: Jane Hendricks ***@***.***>; Mention ***@***.***>
Subject: Re: [MyPureCloud/developer-center-blog] Making of Synoptia -- NEW blog by Ram Sundaram (PR #127)

 EXTERNAL EMAIL - Please use caution with links and attachments

________________________________
Please add links to the API resources and product docs. The developer blog targets a technical audience and needs to include the technical information about how customers can start using this feature and its API resources in their own applications.

—
Reply to this email directly, view it on GitHub<https://github.com/MyPureCloud/developer-center-blog/pull/127#issuecomment-1540457531>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3JRI6YFBP5VPN2DMYM7HALXFJSXNANCNFSM6AAAAAAX2II4QU>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-05-11 14:29 UTC, Sroon101 commented
@timsmithgenesys is this good to go? We're getting a lot of traction around our generative AI and need a resource to quickly point people to

2023-05-11 14:36 UTC, timsmithgenesys commented
@Sroon101 There is still outstanding feedback that has not been addressed. This is also pending final editorial review from 
@carnellj-genesys  and @amallen02.

2023-05-11 15:41 UTC, JaneHendricks commented
@timsmithgenesys colon added, and folder renamed.

2023-05-11 16:19 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +title: How Generative AI is used Genesys Agent Assist
Recommendation: "How to use Generative AI with Genesys Agent Assist" or "How Generative AI is used with Genesys Agent Assist".

2023-05-11 16:35 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +Generative AI is used in Genesys Agent Assist to automatically summarize conversations between customers and agents. The service processes the entire conversation in near real time as part of the age
Generative AI is used in Genesys Agent Assist to automatically summarize conversations between customers and agents. As part of the agent's After Call Work (ACW), the complete conversation is processed in near real time. In the first version, English is the only language supported. Additional languages are being considered. This is the first Generative AI component built by Genesys Cloud. This [article](https://help.mypurecloud.com/articles/create-a-conversation-summary-with-genesys-agent-assist/) describes how Generative AI is used in Agent Assist to create an automatic conversation summary.

2023-05-11 16:39 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +Generative AI is used in Genesys Agent Assist to automatically summarize conversations between customers and agents. The service processes the entire conversation in near real time as part of the age
Remove "an" before "email", remove "a" before "song".

2023-05-11 16:47 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +At a high level, Transformer architecture typically consists of an encoder and decoder. Encoder encodes the input text to a vector representation and can be thought of as an array of floating-point n
"thought of as" - considered

2023-05-11 16:59 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +In some NLP applications like text classification, sentiment analysis, question answering, typically only the encoder is used. In those applications, there is no need to formulate a response through
1st sentence recommendation: "Typically, only the encoder is used in NLP applications such as text classification, sentiment analysis, and question answering."

3rd sentence- "the output of the encoder with..." 
recommendation: "the encoder output with..."

5th sentence - "The class of models that are used..."
recommendation - "The class of models used...."

5th sentence - "and output"
recommendation - "and the output"

2023-05-11 17:03 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +The Genesys Agent Assist's Generative AI service uses Seq2Seq modeling adapted and customized based on an open-source model from **HuggingFace**, a respected open-source community that enterprise dev
Last sentence - "... perspective and using..."
recommendation - Place a period after "perspective" and start new sentence - "Using open-source...."

2023-05-11 17:05 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +* Should have good trade-off between latency and accuracy
"have good..." - "have a good...."

2023-05-11 17:07 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +* Should be supported well and be transparent on what data was used to train the model
"...and be transparent on..." - 
recommendation - "and transparent about..."

Place a period after "model"

2023-05-11 17:14 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +Preprocessing and post processing are very important to ensure we extract maximum accuracy from the model. Some of what agents and customers type during a conversation would confuse the model. Some w
2nd sentence - "would confuse..."
recommendation - "confuse"

3rd sentence - "Some words and concepts..."
recommendation - Split sentence/place a period after "meanings".
Start next sentence with "While..."

Last sentence - "Some of the processing..."
recommendation - "Some processing..."

2023-05-11 17:24 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +We need to be careful and control the kind of text the model generates. We know this is data that is likely to be part of the record for the customer and used by supervisors and other stakeholders. M
1st sentence - "the kind of the model generates."
recommendation - "the text generation model"

2nd sentence - "the record for the customer and.."
recommendation - "the customer's record and.."

3rd sentence - "Most of the commercially..."
recommendation - "Most commercially..."

4th sentence - "Models have to be..."
recommendation - "Models must be..."

2023-05-11 17:27 UTC, amallen02 commented on 2023-05-08-generative-AI-in-agent-assist/index.md
> +Given the role these summaries play for our customers, we wanted to avoid that. As part of the process that generates the summary, we suppress a global list of swear/offensive words. This list will b
2nd sentence - "As part of the process that generates the summary..."
recommendation - "As part of the summary generation process"

Last paragraph - "about how this feature is being used"
recommendation - "about how this feature is used"

2023-05-11 17:39 UTC, amallen02 reviewed
Content review.

2023-05-11 20:21 UTC, JaneHendricks commented
@amallen02 I made all but those changes that would alter the intended meaning. Thanks for the careful review.

2023-05-12 15:49 UTC, JaneHendricks commented
Hi -- is there anything else that's preventing this from moving forward? @Sroon101 FYI

2023-05-12 18:20 UTC, carnellj-genesys approved these changes

2023-05-12 18:20 UTC, carnellj-genesys approved these changes

2023-05-12 18:24 UTC, carnellj-genesys commented
> Hi -- is there anything else that's preventing this from moving forward? @Sroon101 FYI

Hi @JaneHendricks We are almost done and hope to have it merged shortly.  it will then be published sometime next week when we do our next content deploy.

Thanks,
    John

2023-05-12 18:25 UTC, amallen02 approved these changes

2023-05-12 18:26 UTC, merged