[DEVENGAGE-2164] - Blog - AnswerCall and MakeCall via API
MyPureCloud/developer-center-blog pull request #134
Opened 2023-10-03 17:19 UTC by themooks

2023-10-13 16:03 UTC, carnellj-genesys requested changes
Overall really good blog post. Let me know your thoughts on feedback

2023-10-13 16:03 UTC, carnellj-genesys commented on source/2023-09-28-answer-call-via-api/index.md
> +Answering a call using Platform API **is NOT supported** (to be more specific, it is only supported while the phone is on an active persistent connection - the request will not be processed otherwise
Nice.

2023-10-13 16:03 UTC, carnellj-genesys commented on source/2023-09-28-answer-call-via-api/index.md
> +## Appendix A: Sample "*ForceDisconnect*" Architect Inbound Call flow
Do we have a blueprint or accelerator around this?  This sounds like a really good accelerator to have.  Might want to talk to @AgnesCorpuz and see if we should open a separate ticket to create this content.  Really like the flow.  Also do we want to include the sample YAML for the flow here.

2023-10-18 07:41 UTC, themooks commented
Thanks. I think I have taken into account all feedback. Pushing an update now

2023-11-13 21:06 UTC, carnellj-genesys approved these changes

2023-11-13 21:07 UTC, merged