CX as Code Export Capabilites Blog
MyPureCloud/developer-center-blog pull request #137
Opened 2024-03-19 01:45 UTC by jenissabarrera

This blog includes the ff:

- replace_with_datasource
- regex
- include and exclude filter

2024-03-19 01:48 UTC, jenissabarrera commented
Hi @charliecon this blog is for review. Thank you!

2024-03-22 11:19 UTC, charliecon approved these changes
Sorry for the delay. Looks great!

2024-03-22 11:19 UTC, charliecon commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +
I would add a note here that "Test_Group" refers to the exported resource ID, and not the name of the group.

2024-03-22 13:10 UTC, HemanthDogiparthi12 commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +title: Introducing Genesys Cloud TF export in CX as Code
Hi @jenissabarrera 

Are we having another blog for enable_dependency_Resolution ?

2024-03-22 13:10 UTC, HemanthDogiparthi12 commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +If you want to export a specific data source instead of a resource, you may do so using this sample:
If you want to export a specific resource as a data source instead of a resource, you may do so using this sample:

2024-03-22 13:28 UTC, carnellj-genesys requested changes

2024-03-22 13:28 UTC, carnellj-genesys commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +The exclude_filter_resources parameter ensures that resources of type “genesyscloud_routing_queue” are excluded from the export. In your Terraform configuration, you can use regular expressions to se
You should note that the include_fitler and exclude_filter resources are mutually exclusive.  You can not use both of them in the same export.

2024-03-22 13:28 UTC, carnellj-genesys commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +If you want to export a specific data source instead of a resource, you may do so using this sample:
This is not quite right.  You can replace an exported resource as a data source.  A couple of use cases can drive you using this:

1.  You have multiple Terraform projects each with their own backing state.  You might need to look up a resource to reference in your project, but you don't want to export the reference object.  Instead you want to convert it to a data source.

2.  You need to reference an item in your export that you don't want to export but still need to reference.

2024-03-22 13:28 UTC, carnellj-genesys commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +  export_as_hcl = true
You should also have a section on the supported formats for the export (e.g. JSON vs HCL) and you can control whether everything gets exported as a single big file, or broken into smaller files.

2024-03-26 05:24 UTC, jenissabarrera commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +title: Introducing Genesys Cloud TF export in CX as Code
Hi @HemanthDogiparthi12 I'll just include the enable_dependency_resolution functionality in this blog.

2024-03-29 09:02 UTC, jenissabarrera commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +  enable_flow_depends_on = false
Hi @carnellj all changes have been made. Thank you!

2024-04-02 18:25 UTC, jenissabarrera commented
Hi @carnellj let me know if there are still parts of this blog that need to be changed.

2024-04-04 12:49 UTC, carnellj-genesys requested changes

2024-04-04 12:49 UTC, carnellj-genesys commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +  enable_dependency_resolution = false
Hi Jen,

One last thing before we merge.  We should talk specifically about what enable_dependency_resolution will do in a separate section of this blog.  enable_dependency_resolution will specifically export any dependencies that are not listed in your Terraform file.  So for instance if you export a queue and it references a skill if enable_dependency_resolution is false (they default) the queue will export and just reference the guid of the dependent skill_group.  However, if you turn enable_dependency_resolution to true.  The skill group will be exported.  The enable_dependency_resolution will automatically try to export any static dependency associated with an archy flow.  One thing we might to highlight is situations where you want to do a big export but exclude something like visions, you can use the exclude_attributes to exclude specific fields that are to be exported on an object.  If you were to exclude division.id this would exclude any division references on the specific object being exported from being removed

2024-04-09 17:57 UTC, carnellj-genesys approved these changes
One small comment and then ping me or Charlie tomorrow and we can merge it.

2024-04-09 17:57 UTC, carnellj-genesys commented on source/2024-03-15-cx-as-code-export-capabilities/index.md
> +By default, Terraform exports only the dependencies explicitly listed in your configuration. For example, if you export a queue that references a skill, Terraform will include the queue but only refe
Small thing.  Skills and skill group are different things.  You might to change them to make them consistent

2024-04-10 18:36 UTC, merged