Web Messaging Blog
MyPureCloud/developer-center-blog pull request #51
Opened 2021-02-03 21:42 UTC by carnellj

Already reviewed and edited Danna's blog.

2021-02-04 22:14 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +Web messaging is available to Genesys Cloud customers using Genesys Cloud 2 and above, including the Genesys Cloud 1 Digital Upgrade 1.
Web messaging isn't GA and therefore isn't available to customers. This blog post should include instructions for customers to join the beta or we should hold off until it's GA.

2021-02-04 22:16 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +1.	Call **POST /api/v2/webdeployments/configurations**.
call -> make a request to

2021-02-04 22:17 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +    [Sample JSON body](https://developer.mypurecloud.com/api/webmessaging/configure.html#example_messenger_configuration)
Keep this on the same line as above. This is going to create an odd dangling set of words with paragraph padding in the middle of the list.

2021-02-04 22:19 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +- **Default language**: At runtime, we attempt to display the appropriate language for the customer. If this cannot be done, we use the default language you specify. Choose from the available languag
Without a blank line in between, the dashes will continue the ordered list above. If this is meant to be an unordered list, a blank line between the lists is required.

2021-02-04 22:20 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +    - **Journey**: Track how customers navigate your website and build a rich set of journey context data about them. To turn on Genesys Predictive Engagement, in the **journeyEvents** attribute, set
This requires additional licenses, features, and configuration, correct? If so, mention that and link out to some resources for Journey stuff.

2021-02-04 22:22 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +1.	Call **POST /api/v2/webdeployments/configurations/{configurationId}/versions/draft/publish**. Replace {configurationId} with your configuration’s Id value, which was returned in the previous steps
call -> make a request to

Generally, lists should be avoided when there's only one item. Consider making this part of the paragraph.

2021-02-04 22:23 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +Your configuration status automatically changes from Draft to Active. To verify this, call **GET/api/v2/webdeployments/configurations** and check that your configuration ID is listed with Version: 1.
Any issues with eventual consistency here? Is polling or a delay required?

2021-02-04 22:24 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +Any subsequent updates become part of the next draft version, which then becomes Version 2 when you publish it.
Subsequent updates aren't hardcoded to version 2, correct? This should state that the version will be incremented with each update/publish (whatever the case is).

2021-02-04 22:25 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +## Create your web messaging configuration
Why is this all using the API? Shouldn't users typically use the admin UI?

2021-02-04 22:25 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +      [Sample JSON body](https://developer.mypurecloud.com/api/webmessaging/configure.html#example_messenger_deployment)
same comment as above about dangling words in the middle of a list

2021-02-04 22:27 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +```{ "title": "Example single snippet", "language": "JavaScript"}
The language in this block is `html`, not `javascript`. It has to be HTML because the JS code is inside of a script tag; the syntax highlighting is messed up as-is because of this.

2021-02-04 22:27 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +<script type=\"text/javascript\" charset=\"utf-8\">
This isn't valid HTML; remove the escapes on the quotes.

2021-02-04 22:28 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +We’ve only begun to scratch the surface on what is possible through web messaging. For a deep dive into enhanced capabilities please check out our [Developer Center documentation](https://developer.m
Don't include the dev center hostname; just use the path. i.e. `/api/webmessaging/`

2021-02-04 22:29 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +- **Default language**: At runtime, we attempt to display the appropriate language for the customer. If this cannot be done, we use the default language you specify. Choose from the available languag
Don't include the dev center hostname; just use the path. i.e. `/api/webmessaging/configure.html#languages`

2021-02-04 22:29 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +      [Sample JSON body](https://developer.mypurecloud.com/api/webmessaging/configure.html#example_messenger_deployment)
Don't include the dev center hostname; just use the path. i.e. `/api/webmessaging/configure.html#example_messenger_deployment`

2021-02-04 22:30 UTC, timsmithgenesys requested changes
There's a few display issues and links that need to be fixed. Style commentary is optional.

2021-02-05 13:35 UTC, carnellj commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +Web messaging is available to Genesys Cloud customers using Genesys Cloud 2 and above, including the Genesys Cloud 1 Digital Upgrade 1.
I will talk to Chad Hansen on messaging here.  He is the one who wrote the blog post and as the product manager, is responsible for messaging.

2021-02-05 13:37 UTC, carnellj commented
Thanks for the feedback.  I will follow up with Chad and Danna.  Danna actually ported this over from a word doc so I need to provide some feedback about Developer Center URLS.

2021-02-08 15:19 UTC, carnellj commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +## Create your web messaging configuration
There is no Admin UI for the initial release of the product.  The first release will have the configuration published via the API.

2021-02-08 15:40 UTC, carnellj commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +Your configuration status automatically changes from Draft to Active. To verify this, call **GET/api/v2/webdeployments/configurations** and check that your configuration ID is listed with Version: 1.
No talked with Chad.  He has never seen any.

2021-02-08 15:46 UTC, timsmithgenesys commented on source/2021-02-20-Introduction-to-web-messaging/index.html.md
> +<script type="text/javascript" charset="utf-8\">
missed one escape slash

2021-02-08 15:46 UTC, timsmithgenesys approved these changes

2021-02-08 15:59 UTC, merged