DEVENGAGE-614
MyPureCloud/developer-center-blog pull request #73
Opened 2021-05-14 10:59 UTC by PrinceMerluza

Add blog for CLI usage on PowerShell

2021-05-24 17:23 UTC, timsmithgenesys commented
@PrinceMerluza Seriously nice job on the banner image! I was about to ask where you got it from, then realized it's actually a screenshot of using the CLI and not a stock image. 🙌

2021-05-24 17:26 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +date: 2021-05-24
The date in the frontmatter and the date in the folder name should match to avoid confusion.

2021-05-24 17:29 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +**GC-CLI version**: CLI version 11.0.0 is used at the time of writing. Some commands may be different if you're using another version. To determine which one you're using, run `gc.exe version`.
Good disclaimer. Add something to the effect of "You can always find the latest CLI documentation at [link]." to close the loop for readers in the future that will find the disclaimer useful.

2021-05-24 17:30 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +First we need to download the executable from this [page](https://developer.genesys.cloud/api/rest/command-line-interface/). If you are using Windows, then you have to manually place the file in a fo
don't include the domain in links

2021-05-24 17:37 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +If you're unsure how to do the latter, then you can follow these steps to setting up the cli:
"cli" should always be capitalized.

2021-05-24 17:47 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +@{
I'm not familiar with powershell, but does this need slashes at the end of the lines like you do for a bash/shell command? E.g.

```sh
command --foo=bar \
--foo2=bar2 \
--foo3=lastcommand
````

2021-05-24 17:48 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +```shell
language should be json

2021-05-24 17:51 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +```powershell
Code fences don't support the `powershell` language. This should probably highlight ok with just `shell`. You notice it looking particularly bad, let me know and I can look into adding powershell.

2021-05-24 17:56 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +Full script could be found here as a quick-hits [recipe](https://github.com/MyPureCloud/quick-hits-cli/blob/main/notifications/powershell/Connect-NotificationsChannel.ps1).
Nice! Quick hits are meant to be embedded directly in the page. The docs for the syntax aren't published yet, but you can use `<dxui:QuickHit id="Connect-NotificationsChannel" title="Connect Notification Channel" />` to embed it here. Grab the id from the start marker in the quick hit if you have others you want to embed. I'll send you a link to the doc source in chat.

2021-05-24 18:02 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +In the CLI's inception, materials have been focused more for the Unix environments. As developers, it might have been our bias towards an environment we're familiar with or with the fact that a lot o
This could be reworded to sound like less of an apology or consolation; cross-platform support for the CLI was intentional. Maybe frame it as most materials are focused on cross-platform shell commands so we have the widest reach with them, but this blog seeks to address the subset of users working in the Windows-only powershell environment.

2021-05-24 18:04 UTC, timsmithgenesys commented on source/2021-06-01-cli-with-powershell/index.md
> +All this wouldn't have been possible without the feedback and suggestions we received from you so far. We're very excited to hear more as John Carnell's team develop the CLI further.
I'd be much less specific about the dev team here; it's not relevant to external readers. You can probably just say "as we develop" to portray Genesys as a single organization. #OneGenesys :)

2021-05-25 06:17 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +date: 2021-05-24
Fixed

2021-05-25 06:18 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +**GC-CLI version**: CLI version 11.0.0 is used at the time of writing. Some commands may be different if you're using another version. To determine which one you're using, run `gc.exe version`.
Added link

2021-05-25 06:18 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +First we need to download the executable from this [page](https://developer.genesys.cloud/api/rest/command-line-interface/). If you are using Windows, then you have to manually place the file in a fo
Fixed

2021-05-25 06:18 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +If you're unsure how to do the latter, then you can follow these steps to setting up the cli:
Fixed

2021-05-25 06:19 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +@{
No, PowerShell arguments can be multiline.

2021-05-25 06:19 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +```shell
Fixed

2021-05-25 06:22 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +```powershell
Tested it with `shell` and the highlighting actually looks ok so I don't think there's a quick need for adding ps at least for now.

2021-05-25 06:26 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +In the CLI's inception, materials have been focused more for the Unix environments. As developers, it might have been our bias towards an environment we're familiar with or with the fact that a lot o
I agree. Not sure why I wrote that whole spiel but I just skipped it entirely in the new commit. haha

2021-05-25 06:27 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +All this wouldn't have been possible without the feedback and suggestions we received from you so far. We're very excited to hear more as John Carnell's team develop the CLI further.
Fixed

2021-05-25 07:14 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +Full script could be found here as a quick-hits [recipe](https://github.com/MyPureCloud/quick-hits-cli/blob/main/notifications/powershell/Connect-NotificationsChannel.ps1).
Thanks Tim, I was wondering what the START and END markers when I was writing the quick-hits. I'll submit a PR for the quick-hits because I need to fix the naming(has a period), but I already modified the blog post to include the proper name.

2021-05-25 13:20 UTC, timsmithgenesys approved these changes

2021-05-25 16:37 UTC, carnellj requested changes

2021-05-25 16:37 UTC, carnellj commented on source/2021-06-01-cli-with-powershell/index.md
> +(gc.exe queues list -a | ConvertFrom-Json) | Select-Object id
@PrinceMerluza  Can you fix this comment before we move forward with this?

2021-05-25 16:37 UTC, carnellj commented on source/2021-06-01-cli-with-powershell/index.md
> +gc.exe queues list -a | ConvertFrom-Json | Write-Output | Select-Object id
@PrinceMerluza  Can you fix this comment before we move forward with this?

2021-05-26 01:58 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +In this section, we'll briefly touch on a gotcha that needs to be considered when working with different versions of PowerShell.
Fixed

2021-05-26 01:58 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +(gc.exe queues list -a | ConvertFrom-Json) | Select-Object id
Updated the command

2021-05-26 01:59 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +gc.exe queues list -a | ConvertFrom-Json | Write-Output | Select-Object id
Updated command

2021-05-26 01:59 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +    gc.exe skills create
Updated command

2021-05-26 01:59 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +gc.exe skills create -f new-skill.json
Updated command

2021-05-26 01:59 UTC, PrinceMerluza commented on source/2021-06-01-cli-with-powershell/index.md
> +In the CLI's inception, materials have been focused more for the Unix environments. As developers, it might have been our bias towards an environment we're familiar with or with the fact that a lot o
Hi John this is from the first commit, I decided to replace the entire Closing Thoughts section in a newer commit.

2021-05-26 14:56 UTC, carnellj approved these changes

2021-05-26 14:56 UTC, merged