Introduction to Analytics Blog
MyPureCloud/developer-center-blog pull request #76
Opened 2021-06-09 02:15 UTC by jenissabarrera

jenissa.barrera:
  name: Jen Barrera
  title: Associate Developer Evangelist
  company: Genesys
  bio: Been working with Genesys Cloud for 2 years.
  social:
    github: jenissabarrera
![Jen White BG](https://user-images.githubusercontent.com/50225452/121282116-95347b80-c90b-11eb-9b5f-085bf460c56d.jpg)

2021-06-09 14:04 UTC, timsmithgenesys commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +* [Analytics Query Builder developer tool quick start](https://developer.mypurecloud.com/gettingstarted/developer-tools-analytics-query.html)
A few points about these links:

* Don't include the domain in dev center links.
* Don't include file extensions in the links anymore. The site is smart enough to fix this, but it causes an extra redirect when someone clicks on it.
* This particular page has moved on the new site. It is now located at https://developer.genesys.cloud/guides/quickstarts/developer-tools-analytics-query

This link should just be `* [Analytics Query Builder developer tool quick start](/guides/quickstarts/developer-tools-analytics-query)`

2021-06-09 14:05 UTC, timsmithgenesys commented on source/2021-05-10-introduction-to-analytics-api/index.md
> + This is the result when the filters are applied, other data will be filtered out. This will make the result straightforward depending on the user need.
Careful with extra indentation. One space will be ignored, but two or more spaces or any tabs will cause that element to be indented.

2021-06-10 13:40 UTC, timsmithgenesys approved these changes

2021-06-11 16:12 UTC, carnellj requested changes

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +
Hi Jen,

A couple of comments. 

Your opening paragraph is a little weak.  First, you repeat the sentence "There are three data perspectives of data in the Analytics API" twice (almost back to back).  Second, the opening paragraph should really give a good introduction to the topic and give the reader decide why they should spend the time to read this blog."

I would recommend a couple of things:

1.  Start with what the analytics API is used for.  Why do people use it?
2. Spend a few sentences describing the differences between the APIs and then introduce that this blog is going to look at conversation details query.

I don't think this will be a massive life.

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +
With each of your query examples introduce what is the typical use case a Genesys Cloud developer might use the user query.  Is it to understand pull-back metrics about agent performance?  Imagine you are a brand new developer to the contact center space.  Why would you care about issuing this kind of query?  Then get into the details

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +
Same as my early comment.  What would be the use case for this query?  Remember our jobs are not just to explain the mechanics of the query, but also to connect the dots on how they could use this query to solve a business problem.

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +The user can also modify the search and add specific filter. In this case, we will search for inbound and voice data. To do so, go to Segment filters, in the predicates section click on type and sele
predicates section click on type and select Dimension should be "predicates section, click on type, and select Dimension"

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +To search for the available and interacting agents, go to Presence filters, in the predicates section click on dimension and choose systemPresence. Choose available as value.
To search for the available and interacting agents, go to Presence filters, in the predicates section and click on dimension and choose systemPresence. Choose available as value.

should probably read 

"To search for the available and interacting agents, go to Presence filters n the predicates section and click on dimension.  Then choose systemPresence as the dimension. Set the value dropdown to "available".

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +For the Routing Status, go to Routing Status Filters. Select or as type. Under the predicates value choose dimension, on the dimension choose Routing Status. And select Interacting as Value.
any time you referencing the things like a field name or a predicate (e.g. or) you might to make word bolded so it stands out from the rest of the sentence.

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +
I would have a close paragraph that summarizes what the Analytics API is and also what you learned in the blog.

2021-06-11 16:12 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +
You might want to include Maise Harrises Analytics Query Builder tool devcast as a link here.

2021-06-28 02:15 UTC, jenissabarrera commented
Hi @carnellj any updates on this?

2021-06-28 12:52 UTC, carnellj commented
> Hi @carnellj any updates on this?

Sorry about that.  I made comments last week, but did not realize you could not see them because I did not hit the comment button.  I like bitbucket so much better the github :(

2021-07-06 12:10 UTC, carnellj commented on source/2021-05-10-introduction-to-analytics-api/index.md
> +This is a sample result for conversation query. If you want to extract details such as the name of the participant in the call, the caller's phone number, and any other details. This is where you can
Last one Jen:

This is a sample result for conversation query -> This is a sample result for a conversation query

2021-07-06 12:10 UTC, carnellj reviewed
Hey Jen please fix this last thing and then I can merge it.,

2021-07-06 12:35 UTC, jenissabarrera commented
> Hey Jen please fix this last thing and then I can merge it.,

Done applying the final change.

2021-07-06 13:29 UTC, carnellj approved these changes

2021-07-12 19:59 UTC, merged