Vx 2069a
MyPureCloud/developer-center-blog pull request #78
Opened 2021-06-14 12:47 UTC by RonaldTHynes

Created the flow outcome milestones blog.

2021-06-14 13:25 UTC, timsmithgenesys commented on source/2021-06-10-flow-outcome-milestones/index.md
> +For more information refer to https://developer.genesys.cloud/api/rest/v2/analytics/flow_aggregate
Instead of using the full dev center URL, just use `[Flow Aggregate query](/api/rest/v2/analytics/flow_aggregate)`

2021-06-14 13:26 UTC, timsmithgenesys approved these changes

2021-06-15 12:52 UTC, carnellj requested changes

2021-06-15 12:52 UTC, carnellj commented on source/2021-06-10-flow-outcome-milestones/index.md
> +Yes, indirectly. Customers can subscribe to 2 hawk topics to get flow-related metrics: v2.analytics.flow.{id}.aggregates and v2.analytics.flowoutcome.{id}.aggregates. Both contain milestone data for
Customer's dont know what hawk events are.  They should be called notification service events.

2021-06-15 12:52 UTC, carnellj commented on source/2021-06-10-flow-outcome-milestones/index.md
> +For more information refer to [Flow Aggregate query](https://protect-us.mimecast.com/s/zZ-8CDkJ0KfzDw8xu5PqCV?domain=developer.genesys.cloud)
I think accidently posted the mimecast URL in here

2021-06-15 13:05 UTC, RonaldTHynes commented on source/2021-06-10-flow-outcome-milestones/index.md
> +Yes, indirectly. Customers can subscribe to 2 hawk topics to get flow-related metrics: v2.analytics.flow.{id}.aggregates and v2.analytics.flowoutcome.{id}.aggregates. Both contain milestone data for
Good to know, thanks.

2021-06-15 13:06 UTC, RonaldTHynes commented on source/2021-06-10-flow-outcome-milestones/index.md
> +For more information refer to [Flow Aggregate query](https://protect-us.mimecast.com/s/zZ-8CDkJ0KfzDw8xu5PqCV?domain=developer.genesys.cloud)
Thanks, I'll fix it.

2021-06-15 13:27 UTC, carnellj approved these changes

2021-06-15 15:05 UTC, merged