Devengage 891 event streaming in action
MyPureCloud/developer-center-blog pull request #98
Opened 2021-11-30 15:26 UTC by carnellj

2021-11-30 15:32 UTC, beckypowell4dot7 commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +4. Coming Soon: The Genesys Cloud event orchestrator
no need to capitalize "the"

2021-11-30 15:33 UTC, beckypowell4dot7 commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +Not all event-driven architectures use message queueing. Genesys Cloud provides two different message implementations:  a web-socket based solution and AWS event bridge. The web-socket based solution
"EventBridge" < one word and capitalized like so

2021-11-30 15:34 UTC, beckypowell4dot7 commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +- Was originally based on
was originally based on... what?

2021-11-30 15:35 UTC, beckypowell4dot7 commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +- It is geared toward's UI integration (it is the foundational mechanism for how the Genesys Cloud UI is built)
no apostrophe in "towards" - nor should the word be plural

2021-11-30 15:35 UTC, beckypowell4dot7 commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +  - Events are published to an AWS event bridge
"Events are published to AWS EventBridge"

2021-11-30 15:36 UTC, beckypowell4dot7 commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +  - Much better durability.  If event bridge is down, Genesys will store the messages and attempt to resend them for 4 days.
"EventBridge"

2021-11-30 15:37 UTC, beckypowell4dot7 commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +  - Much better durability.  If event bridge is down, Genesys will store the messages and attempt to resend them for 4 days.
You might want to mention that AWS supports a DLQ also: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-rule-dlq.html

2021-11-30 17:45 UTC, carnellj commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +3. Using the Genesys Cloud AWS Event Bridge for event-driven integrations
Fixed.

2021-11-30 17:45 UTC, carnellj commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +4. Coming Soon: The Genesys Cloud event orchestrator
Fixed

2021-11-30 17:46 UTC, carnellj commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +Not all event-driven architectures use message queueing. Genesys Cloud provides two different message implementations:  a web-socket based solution and AWS event bridge. The web-socket based solution
Fixed

2021-11-30 17:51 UTC, carnellj commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +  - Much better durability.  If event bridge is down, Genesys will store the messages and attempt to resend them for 4 days.
Added the link

2021-12-01 18:53 UTC, timsmithgenesys commented
The two diagrams need to use the new Genesys Cloud CX logo. Sending them to you directly.

2021-12-01 19:25 UTC, timsmithgenesys requested changes

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +1. A platform-agnostic, web-socket event implementation
web-socket -> WebSocket

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +Not all event-driven architectures use message queueing. Genesys Cloud provides two different message implementations:  a web-socket based solution and AWS event bridge. The web-socket based solution
web-socket -> WebSocket (2x)

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +1. **No message durability**. Genesys Cloud will only send events over an open WebSocket. If a WebSocket is killed, any events that are generated while the WebSocket will not be queued will not be se
> If a WebSocket is killed,

I might be more general as to why, because unexpected disconnections count here also. Maybe "If a WebSocket connection is closed for any reason,"

> any events that are generated while the WebSocket will not be queued will not be sent or retried

This is missing some words or has some extra words. Does it mean to say "...WebSocket is not open will not be queued, sent, or retried."?

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +2. **WebSockets are a lower-level primitive**. With a WebSocket, you as the developer are responsible for establishing the network connection, handling network connectivity issues , scaling based on
extra space after issues

> are not very complicated taken together they can make

are not very complicated _on their own,_ taken together they can make

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +3. **Limited generalization for to subscribing topics**. When subscribing to topics, you must explicitly know the id of the Genesys Cloud object you are listening to events on. For example, to subscr
> each individual queues.

queues -> queue

> to do and their is

their -> there

> there is no mechanism to say subscribe to tell the notification service to subscribe to events from all queues.

words are a little soupy, maybe reduce to "there is no mechanism to subscribe to events from multiple queues using a single topic"

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +1. [Using the Genesys Cloud CLI to listen to Notification service events](https://www.youtube.com/watch?v=r4Jc-Mn0ONA)
Would be good to also link to https://developer.genesys.cloud/api/rest/v2/notifications/notification_service here for more advanced readers that want to get straight to RTFM.

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +Genesys is continuing to build out the Genesys Cloud event processing capabilities. Up until this point Genesys Cloud allows you to consume messages with your own external integrations via a WebSocke
> Up until this point Genesys Cloud allows you to consume

tense agreement, I think this should say "Currently Genesys Cloud allows..."

> This new capability, called Genesys Cloud Event Orchestrator is currently in beta

add a comma after Orchestrator or remove it after capability. No shrodinger's interjections. :)

> will use Genesys Cloud Architect Workflow to process

Workflow -> Workflows, or "use a Genesys..."

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +The Genesys Cloud EventBridge and the Genesys Cloud Event Orchestration features are properly thought of as opposite sides of the same coin; similar functionality but for very different use cases. Ev
> specific service level guarantees

Do we actually have time-based SLAs? Or does this just mean to convey the robustness of its retry logic? 

> The Genesys Cloud Event Orchestration do not have 

The Genesys Cloud Event Orchestration _feature does_ not have

2021-12-01 19:25 UTC, timsmithgenesys commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +2. **Notification Service using AWS EventBridge**. An enterprise messaging bus suitable for real-time backend data integrations. While it can only be used within the context of a customer's AWS accou
Today is December 2021. Is this availability statement accurate? For the call for beta testers, is there reasonably enough time for someone to read this post, join the beta, and provide feedback before it goes GA before the code freeze in a couple weeks? Just making sure we're not putting out a call to action that's not reasonably actionable.

2021-12-02 16:23 UTC, carnellj commented on source/2021-11-12-2021-Event-Streaming-In-Action/index.md
> +1. A platform-agnostic, web-socket event implementation
Cool.  I  had converted most of the rest to WebSocket, but missed a few

2021-12-02 16:45 UTC, timsmithgenesys approved these changes

2021-12-02 16:46 UTC, timsmithgenesys commented
![approve](https://user-images.githubusercontent.com/74417894/144465738-2a8601b4-3ba3-431b-816f-693bb68826a9.png)

2021-12-02 18:27 UTC, merged