golang-sdk-notification-service
MyPureCloud/developer-center-blog pull request #99
Opened 2021-12-03 17:09 UTC by michaeljroddy

2021-12-06 21:23 UTC, carnellj reviewed
Really good article Michael.  Two comments:

1.  I would put together 2 diagrams.  An object model showing the command interface, command implementations and the factory pattern.  The second diagram should be a sequence diagram showing the process of what happens in the application.
2. I would take a look at some of the names you are using.  I have tried to identify them throughout my comments.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +		log.Fatalf("error creating notifications channel: %v", err)
I would return an err object along with the channel object.  Using a log.Fatalf will cause the service to terminate.  This is going to be a service or server-based app and by returning the Error to the caller trying to start the service you give the developer control over how to handler errors.  By doing a log.Fatalf, you are going to terminate the program using the code.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +	for i, topic := range sns.topics {
I am assuming that sns means SequentialNotificationService.  I would consider renaming this as sns is an amazon service and might confuse people into thinking that that you are using sns.  This is particularly confusing because you do not include the packages you are using.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +**Note:** That we are assigning the value of the topic by writing `&sns.topics[i]`, to the `platformclientv2.Channeltopic` object, using the index to acces this value and not just the value of the co
That we are -> We are 

acces -> access

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +		log.Fatalf("error subscribing to topics: %v", err)
See earlier comments about error handling.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +	topci1,
topci1 -> topic1
topci2 -> topic2

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +Then we call `PostNotificationsChannelSubscriptions()` and pass in the `reqbody` and the `channelId`. The request returns three values, `*Channeltopicentitylisting`, `*APIResponse` and `error`, but w
Third sentence reads very clumsily

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +To begin, lets create a channel of type `os.Signal`. The channel will be used to send `os.Signal` values  as we want to close our web socket connection and exit the program on `SIGINT` or `ctrl^C`. T
I would explicitly call out you are using golang channels instead of the term generic channel.  The problem is that we also have the concept of channels in the notification service.  So if you use the generic term channel the reader can be confused as to what channel you are referring to.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +	if err != nil {
See comments on error

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +	u := url.URL{Scheme: connectUri[0:3], Host: connectUri[6:31], Path: connectUri[32:]}
Ask @timsmithgenesys how we can do these using regular expressions.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +		if err != nil {
Definitely should not be using a log.Fatalf.  One bad message will cause your entire service to "crap" its pants.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +`getMessageType()` macthes the message `string` against three different patterns and returns the corresponding message type if the pattern macthes. If the pattern does not match, the `error` is retur
macthes->matches

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +func NewHeartbeat(message string) *heartbeat {
I would just call this New instead of NewHeartbeat.  You might event want to put the New as part of the Command interfaces.

2021-12-06 21:23 UTC, carnellj commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +func NewRoutingQueuesIdUsers(message string) *routingQueuesIdUsers {
See earlier comments

2021-12-07 08:28 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +With the Genesys Cloud Notification Service, you can create a notifications channel, subscribe the channel to a topic (or multiple topics) and listen for notification events from Genesys Cloud by ope
opeing -> opening

2021-12-07 08:30 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +Lets begin by writing the `notification_service_interface.go` file.
Lets -> Let's

2021-12-07 08:30 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +import "github.com/mypurecloud/platform-client-sdk-go/v56/platformclientv2"
You have v57 in the go get command so this should be the same

2021-12-07 08:32 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +To begin, lets create the notification service struct. Here you can see that the sequential notification service `struct` contains a `topics` variable of type `[]string`. The `topics` variable will h
lets -> let's (let us)

2021-12-07 08:32 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +Now lets write the constructor function that will be used to create an instance of the sequential notification service in our main function. The constructor function will be passed a slice of **topic
lets -> let's

2021-12-07 08:37 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +`connection.ReadMessage()` returns three values, but we are only concered with the message instelf and the `error`.
concered -> concerned

2021-12-07 08:37 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +`connection.ReadMessage()` returns three values, but we are only concered with the message instelf and the `error`.
instelf -> itself

2021-12-07 08:41 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +	"github.com/MyPureCloud/golang-sdk-notification-service.git/command_interface"
The .git wouldn't be necessary here

2021-12-07 08:42 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +	"github.com/MyPureCloud/golang-sdk-notification-service.git/sequential_notification_service"
Same comment about .git

2021-12-07 08:43 UTC, ronanwatkins commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +	topic1 := os.Getenv("USERS_ID_PRESENCE")
I haven't seen any notes about setting these env vars

2021-12-07 15:22 UTC, timsmithgenesys commented on source/2021-12-03-golang-sdk-notification-service/index.md
> +With the Genesys Cloud Notification Service, you can create a notifications channel, subscribe the channel to a topic (or multiple topics) and listen for notification events from Genesys Cloud by ope
Break this up into 2-3 paragraphs; it's too long as one.

2021-12-07 16:12 UTC, timsmithgenesys requested changes

2021-12-16 17:37 UTC, merged